sudo : required
services : 
        - docker

before install :
        - docker build -t ajishkp/docker-react -f Dockerfile.dev . 
script :
    - docker run ajishkp/docker-react npm run test -- -- coverage
